### PR TITLE
Erc4337

### PR DESCRIPTION
**Pull request by d4v1d03**
DB proofs - ```{"_id":{"$oid":"668d049d4175d96e8e4552c6"},"id":"20263232","transactionHashesWithUserOps":["0xd7c22ab73ffe868986a6ec02891ccf84f81dd65b82c326b907a386c9afd2e509"],"entityId":"Block","blocknumber":{"$numberInt":"20263232"},"chainId":"1","instanceId":"abdb4b2f-4d72-4c61-a5de-5689e0e3ee4f"}```

### CODE REVIEW

**Comment by d4v1d03** [comment]
```{"_id":{"$oid":"668d049e4175d96e8e4552d1"},"id":"0xd7c22ab73ffe868986a6ec02891ccf84f81dd65b82c326b907a386c9afd2e509","userOpHashes":["0x37d2e9408fc387236682cc3aba490b43fff2b941e7f2dc4469fd73add83d36b1"],"entityId":"Transaction","blocknumber":{"$numberInt":"20263232"},"chainId":"1","instanceId":"abdb4b2f-4d72-4c61-a5de-5689e0e3ee4f","gasLimit":"6193040","gasPrice":"5151356889","transactionHash":"0xd7c22ab73ffe868986a6ec02891ccf84f81dd65b82c326b907a386c9afd2e509"}


{"_id":{"$oid":"668d049e4175d96e8e4552d4"},"id":"0x37d2e9408fc387236682cc3aba490b43fff2b941e7f2dc4469fd73add83d36b1","entityId":"UserOperation","blocknumber":{"$numberInt":"20263232"},"chainId":"1","instanceId":"abdb4b2f-4d72-4c61-a5de-5689e0e3ee4f","beneficiary":"0xD58AA88246a1CF56A48E8e184405bd7ef0BE7B83","callData":"0x940d3c600000000000000000000000008ae01fcf7c655655ff2c6ef907b8b4718ab4e17c00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000001448d80ff0a000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000ee00d58aa88246a1cf56a48e8e184405bd7ef0be7b83000000000000000000000000000000000000000000000000001641fbfb84900000000000000000000000000000000000000000000000000000000000000000000062de59c08eb5dae4b7e6f7a8cad3006d6965ec1600000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044c8393ba9000000000000000000000000ae7ab96520de3a18e5e111b5eaab095312d7fe840000000000000000000000000000000000000000000000000e010b1a82d8c00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","initCode":"0x","maxFeePerGas":"0","maxPriorityFeePerGas":"0","nonce":{"$numberInt":"8"},"paymasterAndData":"0x","preVerificationGas":"0","sender":"0xd7fe5710cc34d48bd050705d3f4a36343dbdf9c7","signature":"0xd32198241af18f7460109a83373785e260aa7f73ceb54b9f2b0cb43211285bb732628450f7285a045fb799b4712ed33c37b71c600c01fed438e0354b76e8fbbe1b","verificationGasLimit":"3000000","ERC20Data":"[{\"ERC20TransferAmount\":\"1009100000000000000\",\"ERC20TransferFrom\":\"0x000000000000000000000000d7fe5710cc34d48bd050705d3f4a36343dbdf9c7\",\"ERC20TransferTo\":\"0x00000000000000000000000062de59c08eb5dae4b7e6f7a8cad3006d6965ec16\"}]","actualGasCost":{"$numberInt":"0"},"actualGasUsed":{"$numberInt":"824342"},"bundler":"0xd58aa88246a1cf56a48e8e184405bd7ef0be7b83","createdAt":"1720459139","entryPoint":"0x5ff137d4b0fdcd49dca30c7cf57e578a026d2789","network":"mainnet","paymaster":"0x0000000000000000000000000000000000000000","success":true,"txHash":"0xd7c22ab73ffe868986a6ec02891ccf84f81dd65b82c326b907a386c9afd2e509"}

{"_id":{"$oid":"668d049e4175d96e8e4552e0"},"id":"0xd7c22ab73ffe868986a6ec02891ccf84f81dd65b82c326b907a386c9afd2e509","numberOfLogs":{"$numberInt":"5"},"JSONdata":["{\"log_index\":\"459\",\"log_transaction_hash\":\"0xd7c22ab73ffe868986a6ec02891ccf84f81dd65b82c326b907a386c9afd2e509\",\"log_transaction_index\":\"147\",\"log_address\":\"0x5ff137d4b0fdcd49dca30c7cf57e578a026d2789\",\"log_data\":\"0x\",\"topics\":[\"0xbb47ee3e183a558b1a2ff0874b079f3fc5478b7454eacf2bfc5af2ff5878f972\"]}","{\"log_index\":\"460\",\"log_transaction_hash\":\"0xd7c22ab73ffe868986a6ec02891ccf84f81dd65b82c326b907a386c9afd2e509\",\"log_transaction_index\":\"147\",\"log_address\":\"0xa1290d69c65a6fe4df752f95823fae25cb99e5a7\",\"log_data\":\"0x0000000000000000000000000000000000000000000000000000000000000000\",\"topics\":[\"0x8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b2291e5b200ac8c7c3b925\",\"0x000000000000000000000000d7fe5710cc34d48bd050705d3f4a36343dbdf9c7\",\"0x00000000000000000000000062de59c08eb5dae4b7e6f7a8cad3006d6965ec16\"]}","{\"log_index\":\"461\",\"log_transaction_hash\":\"0xd7c22ab73ffe868986a6ec02891ccf84f81dd65b82c326b907a386c9afd2e509\",\"log_transaction_index\":\"147\",\"log_address\":\"0xa1290d69c65a6fe4df752f95823fae25cb99e5a7\",\"log_data\":\"0x0000000000000000000000000000000000000000000000000e010b1a82d8c000\",\"topics\":[\"0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef\",\"0x000000000000000000000000d7fe5710cc34d48bd050705d3f4a36343dbdf9c7\",\"0x00000000000000000000000062de59c08eb5dae4b7e6f7a8cad3006d6965ec16\"]}","{\"log_index\":\"462\",\"log_transaction_hash\":\"0xd7c22ab73ffe868986a6ec02891ccf84f81dd65b82c326b907a386c9afd2e509\",\"log_transaction_index\":\"147\",\"log_address\":\"0x62de59c08eb5dae4b7e6f7a8cad3006d6965ec16\",\"log_data\":\"0x0000000000000000000000000000000000000000000000000e010b1a82d8c000\",\"topics\":[\"0xd1ff36888873897951eaf991bca7db625b8ed70bf2b0d54441907bdab02b08d7\",\"0x000000000000000000000000d7fe5710cc34d48bd050705d3f4a36343dbdf9c7\",\"0x000000000000000000000000ae7ab96520de3a18e5e111b5eaab095312d7fe84\",\"0x0000000000000000000000000000000000000000000000000000000000000515\"]}","{\"log_index\":\"463\",\"log_transaction_hash\":\"0xd7c22ab73ffe868986a6ec02891ccf84f81dd65b82c326b907a386c9afd2e509\",\"log_transaction_index\":\"147\",\"log_address\":\"0x5ff137d4b0fdcd49dca30c7cf57e578a026d2789\",\"log_data\":\"0x00000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c9416\",\"topics\":[\"0x49628fd1471006c1482da88028e9ce4dbb080b815c9b0344d39e5a8e6ec1419f\",\"0x37d2e9408fc387236682cc3aba490b43fff2b941e7f2dc4469fd73add83d36b1\",\"0x000000000000000000000000d7fe5710cc34d48bd050705d3f4a36343dbdf9c7\",\"0x0000000000000000000000000000000000000000000000000000000000000000\"]}"],"entityId":"UserOpLogs","blocknumber":{"$numberInt":"20263232"},"chainId":"1","instanceId":"abdb4b2f-4d72-4c61-a5de-5689e0e3ee4f"}

{"_id":{"$oid":"668d049e4175d96e8e4552ea"},"id":"ETH","totalAccount":"0","totalOperations":"1","entityId":"Blockchain","blocknumber":{"$numberInt":"20263232"},"chainId":"1","instanceId":"abdb4b2f-4d72-4c61-a5de-5689e0e3ee4f"}



{"_id":{"$oid":"668d049e4175d96e8e4552f3"},"id":"0x0000000000000000000000000000000000000000","ops":["0x37d2e9408fc387236682cc3aba490b43fff2b941e7f2dc4469fd73add83d36b1"],"createdAt":"1720459139","totalOperations":"1","gasSponsored":"824342824342","entityId":"Paymaster","blocknumber":{"$numberInt":"20263232"},"chainId":"1","instanceId":"abdb4b2f-4d72-4c61-a5de-5689e0e3ee4f","updatedAt":"1720459139"}

{"_id":{"$oid":"668d049e4175d96e8e4552f3"},"id":"0x0000000000000000000000000000000000000000","ops":["0x37d2e9408fc387236682cc3aba490b43fff2b941e7f2dc4469fd73add83d36b1"],"createdAt":"1720459139","totalOperations":"1","gasSponsored":"824342824342","entityId":"Paymaster","blocknumber":{"$numberInt":"20263232"},"chainId":"1","instanceId":"abdb4b2f-4d72-4c61-a5de-5689e0e3ee4f","updatedAt":"1720459139"}

{"_id":{"$oid":"668d049f4175d96e8e4552fc"},"id":"0xd58aa88246a1cf56a48e8e184405bd7ef0be7b83","ops":["0x37d2e9408fc387236682cc3aba490b43fff2b941e7f2dc4469fd73add83d36b1"],"createdAt":"1720459139","totalOperations":"1","sender":"0xD7fE5710Cc34d48Bd050705d3F4a36343dBDf9C7","target":"0x5ff137d4b0fdcd49dca30c7cf57e578a026d2789","fee":"","gasCollected":"824342824342","entityId":"Bundler","blocknumber":{"$numberInt":"20263232"},"chainId":"1","instanceId":"abdb4b2f-4d72-4c61-a5de-5689e0e3ee4f","updatedAt":"1720459139"}


{"_id":{"$oid":"668d049f4175d96e8e455308"},"id":"0xd7fe5710cc34d48bd050705d3f4a36343dbdf9c7","ops":["0x37d2e9408fc387236682cc3aba490b43fff2b941e7f2dc4469fd73add83d36b1"],"paymaster":"0x0000000000000000000000000000000000000000","createdAt":"1720459139","createdHash":"0xd7c22ab73ffe868986a6ec02891ccf84f81dd65b82c326b907a386c9afd2e509","createdOpHash":"0x37d2e9408fc387236682cc3aba490b43fff2b941e7f2dc4469fd73add83d36b1","totalOperations":"1","entityId":"Account","blocknumber":{"$numberInt":"20263232"},"chainId":"1","instanceId":"abdb4b2f-4d72-4c61-a5de-5689e0e3ee4f","updatedAt":"1720459139"}```

**Comment by d4v1d03** [comment]
Transaction DB 
image

**Comment by d4v1d03** [comment]
UserOp db - 
image

**Comment by d4v1d03** [comment]
useroplogs db , in this PR 
image

**Comment by d4v1d03** [comment]
Blockchain db - 
image

**Comment by d4v1d03** [comment]
paymaster db -
image

**Comment by d4v1d03** [comment]
bundler db 
image

**Comment by d4v1d03** [comment]
account db - 
image

**Review by pradyuman-verma — APPROVED** [review]

**Pull request merged**
